version: '3.8'

services:
  db:
    image: postgres:17.0
    container_name: postgres-db
    environment:
      POSTGRES_USER: apollolytics
      POSTGRES_PASSWORD: apollolytics
      POSTGRES_DB: apollolytics
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
